### ISSUE TITLE
Penser à jerter les id

### ISSUE THREAD

**Issue by kmodry** [smumu/UnsocialClub#1]
Les id de db sur les vm supinternet ont l'air d'être les vraies dans le fichier de conf.

**Comment by smumu** [comment]
Tu veux dire le serveur, le user et le password ? C'est vrai, mais la VM n'existe plus, donc plus de DB ... Faudrait désindexer le fichier pour les changes, il servira juste d'exemple à modifier, ou alors le renommer en db.php.example.

**Comment by kmodry** [comment]
Ouaip, bref c'état just pour utiliser un ticket :p

**Comment by smumu** [comment]
T'es chiant le repo était propre à ce niveau :(
